[tool.poetry]
name = "dragon"
version = "0.8.5"
description = "private shared tools module."
authors = ["Kaluckii"]

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.17.0"
fastapi = "^0.115.6"
pytz = "^2024.2"